### ISSUE TITLE
hahaha this's good work. It so wonderful.. But..

### ISSUE THREAD

**Issue by yechankun** [Miyuyami/MS2Tools#4]
Isn't it so illegal method?? How did U get the key at Maple2?
It's seems t b little vague..
but I wanna know, How can I try it. 

Sorry for my poor vocabulary. I'm Korean so I have not choice. It's hard to learn more right now.
I can't trust the translator. So, i'm set the order myself.

**Comment by Miyuyami** [comment]
I don't understand what are you trying to accomplish, where are you having an issue? There's a set of instructions of how to use the tools in the README.md (which is also displayed under the files in the main folder).
What do you mean by "key at Maple2"? Are you talking about the cryptography key used to decrypt the files? I got it off the files themselves.
